### ISSUE TITLE
Proxy fails to connect to cluster in KRaft mode when broker ports restricted to 1

### ISSUE THREAD

**Issue by katheris** [kroxylicious/kroxylicious#1045]
**Describe the bug**
When using the Kroxylicious proxy to connect to a Kafka cluster that is running in KRaft mode it is incorrectly requesting ports. Specifically I saw this when running with a single combined node and setting `numberOfBrokerPorts` to 1.

**To Reproduce**
1. Follow the steps in the Kafka quickstart to start a single Kafka node in KRaft mode: https://kafka.apache.org/quickstart
2. Start Kroxylicious with `numberOfBrokerPorts` set to 1
3. Try to list Kafka topics: `./bin/kafka-topics.sh --bootstrap-server localhost:9192 --list`
4. The command hangs and Kroxylicious logs the error "Cannot generate broker address for node id 1"
5. Performing the same steps with a single Zookeeper node and single Kafka node in Zookeeper mode works as expected and does not fail.

**Expected behavior**
The proxy should successfully use the ports 9192 and 9193 to proxy traffic.

**YAML files and logs**

Config yaml used:
```
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
        numberOfBrokerPorts: 1
    logNetwork: false
    logFrames: false
```

Error logged:
```
2024-02-28 10:00:49 <KQueueEventLoopGroup-5-7> WARN  io.kroxylicious.proxy.internal.FilterHandler:293 - [id: 0xee3cf6a7, L:/127.0.0.1:49790 - R:localhost/127.0.0.1:9092]: Filterresponse for BrokerAddressFilter@376749768 METADATA ended exceptionally - closing connection. Cause message java.lang.IllegalArgumentException: Cannot generate broker address for node id 1 as port 9194 would fall outside port range 9193-9193 that is defined for provider with downstream bootstrap localhost:9192)
```
