### ISSUE TITLE
Allow kroxy to present admin HTTPS endpoint

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#110]
As part of supporting [prometheus metrics](https://github.com/kroxylicious/kroxylicious/pull/95) we have added an adminHttp endpoint. Meanwhile [SSL/TLS support](
https://github.com/kroxylicious/kroxylicious/pull/103) has been added to the main proxy endpoint, it would be great to add matching configuration for the admin endpoint.

### example config
```
adminHttp:
  keystoreFile: "/tmp/keystore"
  keyPassword: "password123"
  endpoints:
    prometheus: {}
```
would configure 0.0.0.0:9193 to be SSL protected
