### ISSUE TITLE
AWS KMS - support authentication from instance metadata of EC2

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1294]
**Is your feature request related to a problem? Please describe.**

This issue separates out one of the two enhancement requests described by https://github.com/kroxylicious/kroxylicious/issues/1282.

Currently the proxy requires a long-lived AWS access key/secret key combination to authenticate to AWS. Whilst this
authentication is supported, as it not seen as the most secure option.

For use cases when the proxy binary is running directly on Amazon EC2,  the preferred option is for the EC2 instance to be associated with an IAM role, then the application [fetch short lived credentials from the instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials).  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by k-wall** [comment]
## EC2
> if the proxy binary is running in EC2 then the credentials can be [fetched from the instance medatadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials);

I am understanding that AWS lets you create an IAM role and attach it to an EC2 instance during or after launch.  This role is accessible to applications running on the EC2 instance via a link local address.

From a **quick** look, it appears doable.   `AwsKmsService`'s authentication mechanism needs to become pluggable so that it is capable of specifying alternative authentication mechanism:

what we have today would be re-expressed like this:

```yaml
kms: AwsKmsService                                            
kmsConfig:
  endpointUrl: https://kms.<region>.amazonaws.com             
  authenticationMechanism: AccessKey
  accessKey:
    passwordFile: /opt/aws/accessKey                          
  secretKey:
    passwordFile: /opt/aws/secretKey                 
```

The use cases using an IAM Role, it would be something like this:

```yaml
kms: AwsKmsService                                            
kmsConfig:
  ...             
  authenticationMechanism: IamRole
  role: foo
```

The `AwsKmsService` would take responsibility to call the instance's link local address to get the token and get an accessKey/secretKey using it.  It would also take responsibility to refresh the credentials before they [expire](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#:~:text=We%20make%20new%20credentials%20available%20at%20least%20five%20minutes%20before%20the%20expiration%20of%20the%20old%20credentials.) (background thread required).

Basically I think we'd need to code the equivalent of the [`curl` statements](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).    On the surface, it doesn't look too hard.   We'd need to think about integration testing.  My next steps would be to read the docs more closely and experiment on an EC2 instance
