### ISSUE TITLE
Record Validation Filter: zero-ack produce requests combined with partial batch forwarding causes memory leak and OOM

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#1436]
**Describe the bug**

If I have a RecordValidationFilter with `forwardPartialRequests` enabled, and a producer that is producing lots of zero-ack produce requests we are leaking memory.

1. We put data in a correlation map about the failed topic partitions and then expect to augment them back into the response.
2. In the zero-ack produce request case there is no response to augment and the correlated data sits in the map forever
3. This can grow until OOM

**To Reproduce**

1. run up a kafka broker on 9092

Configure a filter that blocks null values on all topics with forwardPartialRequests enabled

```yaml
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
    logNetwork: false
    logFrames: false
filters:
- type: RecordValidation
  config:
      rules: []
      defaultRule:
        valueRule:
          allowNulls: false                                                 
          allowEmpty: true
      forwardPartialRequests: true
```

hammer the proxy with zero-ack produce requests where some partitions contain only invalid records and some partitions contain only valid records to prompt the partial request forwarding logic to kick in.

```
package org.example;

import org.apache.kafka.clients.admin.Admin;
import org.apache.kafka.clients.admin.AdminClientConfig;
import org.apache.kafka.clients.admin.NewTopic;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

import java.util.List;
import java.util.Map;

public class Main {
    public static void main(String[] args) {
        Admin admin = Admin.create(Map.of(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092"));
        int numPartitions = 20;
        String topic = "test5";
        try {
            admin.createTopics(List.of(new NewTopic(topic, numPartitions, (short) 1))).all().get();
        } catch (Exception e) {
            System.out.println(e);
        }
        KafkaProducer<String, String> producer = new KafkaProducer<>(Map.of(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9192", ProducerConfig.LINGER_MS_CONFIG, 1000, ProducerConfig.ACKS_CONFIG, "0"), new StringSerializer(), new StringSerializer());
        int i = 0;
        while(true) {
            int partition = i++ % numPartitions;
            producer.send(new ProducerRecord<>(topic, partition, "key", partition % 2 == 0 ? null : "it's present"));
        }
    }
}
```

observe Kroxylicious memory in jconsole or equivalent head to the heap limit and requests eventually start to slow down to a crawl:
![Screenshot from 2024-08-16 15-45-09](https://github.com/user-attachments/assets/d7f977e4-1023-4b97-aee3-9f690d054248)

**Expected behavior**

Not a big old memory leak, that's for sure.

It's unclear what record validation bejaviour should be in the context of zero-ack requests. The producer is firing and forgetting, with no response from the broker expected. We still want to prevent the bad data hitting the broker. Maybe we need some metrics to let the user know we are preventing writes.

We also need to ensure we do not respond to zero-ack requests. Currently we respond from the filter if we invalidate the whole ProduceRequest because all topic-partitions contain invalid records or we are transactional and any record in the request was invalid.
