### ISSUE TITLE
RecordEncryption in 0.8.0 closes the client connection with `RequestNotSatisfiable`("failed to reserve an EDEK to encrypt N records...") under load

### ISSUE THREAD

**Issue by ddaviesbrackett-dwp** [kroxylicious/kroxylicious#1526]
**Describe the bug**
RecordEncryptionFilter in Kroxylicious 0.8.0 closes the client connection with a `RequestNotSatisfiable` exception with a message that begins "failed to reserve an EDEK to encrypt N records" under load when using AWS KMS

**To Reproduce**
1. Configure kroxylicious to use record encryption with AWS KMS, setting max encryptions per DEK unreasonably low (say, 5000), using a single KEK (i.e. do not use $topicName in the KEK selector alias). 
2. Fire a reasonably large number of messages at the proxy - ~3000/second in our test
3. See [RequestNotSatisfiable exception log messages](https://github.com/kroxylicious/kroxylicious/blob/40c71dab8330d110e1e3e2cce1153c7bc79948e8/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java#L118) in the kroxy logs

NB: setting the max encryptions per dek very low in step 1 is not strictly necessary, but does increase the prevalence of the error message.

**Expected behavior**
Kroxy should block  during record production until a DEK is available that can satisfy the request (at least if acks != none). 

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
```
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  [redacted]:
    tls:
      key:
        privateKeyFile: [redacted]
        certificateFile: [redacted]
      trust:
        storeFile: [redacted]
        storePassword:
          password: [redacted]
        storeType: PKCS12
    targetCluster:
      bootstrap_servers: [redacted-broker-1]:9094,[redacted-broker-2]:9094,[redacted-broker-3]:9094
      tls:
        key:
          privateKeyFile: [redacted]
          certificateFile: [redacted]
        trust:
          storeFile: [redacted]
          storePassword:
            password: [redacted]
          storeType: PKCS12
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: [redacted-proxy]:9192
        brokerStartPort: 9193
        numberOfBrokerPorts: 4
    logNetwork: false
    logFrames: false
filters:
- type: RecordEncryption
  config:
    kms: AwsKmsService
    kmsConfig:
      endpointUrl: https://kms.eu-west-2.amazonaws.com
      tls:
      accessKey:
        passwordFile: [redacted]
      secretKey:
        passwordFile: [redacted]
      region: eu-west-2
    selector: TemplateKekSelector
    selectorConfig:
      template: "some-redacted-value-containing-no-replacement-tokens"
    experimental:
      encryptionDekRefreshAfterWriteSeconds: 3600
      encryptionDekExpireAfterWriteSeconds: 7200
      maxEncryptionsPerDek: 5007
```

Attach or copy and paste relevant logs.
```
2024-09-23 10:17:03 <nioEventLoopGroup-5-2> WARN  io.kroxylicious.filter.encryption.RecordEncryptionFilter:106 - failed to encrypt records, cause message: io.kroxylicious.filter.encryption.encrypt.RequestNotSatisfiable: failed to reserve an EDEK to encrypt 99 records for topic uk.gov.dwp.test.performance.0 partition 0 after 3 attempts
2024-09-23 10:17:03 <nioEventLoopGroup-5-2> WARN  io.kroxylicious.proxy.internal.FilterHandler:289 - [id: 0xe9b77889, L:/XXX.XXX.XXX.XXX:56406 - R:broker_hostname/XXX.XXX.XXX.XXX:9094]: Filterrequest for RecordEncryptionFilter@1224749844 PRODUCE ended exceptionally - closing connection. Cause message io.kroxylicious.filter.encryption.encrypt.RequestNotSatisfiable: failed to reserve an EDEK to encrypt 99 records for topic uk.gov.dwp.test.performance.0 partition 0 after 3 attempts
``` 
**Additional context**
* We've only run this with AWS KMS, not with either of the other two KMS implementations; this bug may not be dependent on the kms impl but also it might be!!
* We have the capacity to execute variations on the tests above if doing so would help either characterise, or prove resolution of, the issue
* We believe this issue to be something to do with a cross-thread race condition in the Caffeine cache that actually caches the EDEKs, or possibly a too-quick (or parallel? eep) reexecution of the recursive invocations of `attemptEncrypt`. We haven't done any hacking on this to try to fix it yet.
