### ISSUE TITLE
Container resource requests and limits

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#1575]
The Proxy CR should allow to configure container resource requests and limits (e.g. memory and CPU)

**Comment by k-wall** [comment]
The Proxy CR design proposal https://github.com/kroxylicious/design/blob/main/proposals/001-kroxylicious-operator-api-v1alpha.md#kafkaproxy includes the ability to apply limits to the operand pod.

**Comment by tombentley** [comment]
We should do a little research to understand whether we can do this using SSA and how compatible that would be with gitops approaches. Based on that we can decide what we need to do here.

**Comment by robobario** [comment]
still essential to have some way to specify cpu/memory requests/limits

**Comment by robobario** [comment]
trying to wring out the alternative idea from [2080](https://github.com/kroxylicious/kroxylicious/issues/2080) and apply it to requests/limits

We have the Operator manifesting all the resources required (with SSA, which is used by default with JOSDK from what I googled). It's responsible for spinning up numerous Services, ConfigMaps and a proxy Deployment. The suggestion is that the user can annotate/label the dependant objects directly so the operator wouldn't have to know how to apply the users custom labels/metadata.

So is the ask that users would understand all of our DerivedResources and their names? Also I think there's order of operations issues, like with kubectl I can `apply --server-side-apply` a CR like:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    usero: def
  name: simple-sni
  namespace: my-proxy
```
only after `simple-sni` has been created by the Operator. (it looks like it combines neatly with the operator supplied labels).

What is the benefit of doing this for requests/limits? I think the Operator has to have a say in these values as we should be specifying a default. We don't want to get scheduled to a node without enough memory so should be supplying requests. If we are in the business of supplying the default, then the client can't set that values with SSA as the operator would own those fields (if I'm getting the SSA thing)

**Comment by robobario** [comment]
The original proposal was:

```yaml
apiVersion: kroxylicious.io/v1alpha1
kind: KafkaProxy
metadata:
  name: myproxy
spec:
   # Optional - controls the KafkaProxy infrastructure.
   infrastructure:
      # Influences the annotations and labels on all resources created by the operator.
      annotations:
         x: y
      labels:
         x: y
      proxy:
        # Controls specific to operand deployment
        replicas: 2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
```

One thing I'm wondering is whether `proxy` should be a PodTemplate, so it would look like:

```yaml
      proxy:
        spec:
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
```
then in future if we wanted to enable users to specify some metadata for the pod (depends on whether we decided this a user responsibility or operator) via this API we could also allow a `metadata` property.

**Comment by robobario** [comment]
to capture some out-of-band discussions we decided to go with:

```
kind: KafkaProxy
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: minimal
  namespace: proxy-ns
spec:
  infrastructure:
    proxyContainer:
      resources:
        limits:
          "cpu": "50m"
          "memory": "52Mi"
        requests:
          "cpu": "100m"
          "memory": "102Mi"
```

where `infrastructure` is an optional container for platform-level configuration and we use optional sub-properties to target the specific components we want to configure.

here we use a `proxyContainer` property to configure the proxy container, specifying the `resources`.

We decided that we didn't want to commit to mirroring the DeploymentSpec or PodSpec structure within KafkaProxy or we would risk having to eternally synchronize with what users expect to be able to do with it. Instead we have other ideas about how to give users control in future, like we could potentially enable them to reference a separate PodSpec resource to control the proxy pod in depth.
