### ISSUE TITLE
Enable proxy to advertise SNI brokers on a port other than the listening port

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#1760]
Users may wish to use technology like Openshift ingress routes to conveniently expose their cluster to the outside world. This adds another layer of proxying where the port the client connects to may differ from the listening port in the pod. By default in Openshift a TLS passthrough route will be available on port 443. 

Say we have:
1. a proxy with a VirtualCluster configured with SNI with a bootstrap address of `my-proxy-bootstrap.apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com:9092` and a brokerPattern of `my-proxy-broker-$(nodeId).apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com:9092`.
2. we have a ClusterIP service my-cluster-service set up exposing 9092:9092
3. we have a route for `my-proxy-bootstrap.apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com` targeting  `my-cluster-service:9092`
4. we have a route for `my-proxy-broker-0.apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com` targeting  `my-cluster-service:9092`

The client will bootstrap with `my-proxy-bootstrap.apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com:443`, but the proxy will tell the client it can reach broker 0 on `my-proxy-broker-0.apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com:9092`.

I think we should enable the user to specify an optional advertisedPort for SNI:

```
clusterNetworkAddressConfigProvider:
          type: SniRoutingClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: mycluster-proxy.kafka:9092
            brokerAddressPattern: broker$(nodeId).mycluster-proxy.kafka
            advertisedPort: 443
```

and prefer this port when we are advertising the broker addresses to the client.

**Comment by k-wall** [comment]
In the case where the proxy is exposed using OpenShift routes, wouldn't you just have the proxy bind to 443?

```
clusterNetworkAddressConfigProvider:
          type: SniRoutingClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: localhost:443
            brokerAddressPattern: my-proxy-broker-$(nodeId).apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com
```

**Comment by robobario** [comment]
When I tried today it was complaining about not having permission to bind to 443. Haven't looked deeper yet.

But yes, it's another option to coordinate everything to be on the same port.

**Comment by k-wall** [comment]
> When I tried today it was complaining about not having permission to bind to 443. Haven't looked deeper yet.

Ah, yes of course.  It is a < 1024 is a privileged port, so the process would need to be root (which we wouldn't want).

Your  `advertisedPort` idea does make sense, although maybe it would be better to refactor the config so we'd permit something like:

```
clusterNetworkAddressConfigProvider:
          type: SniRoutingClusterNetworkAddressConfigProvider
          config:
            listenAddress: localhost:9092
            advertisedBrokerAddressPattern: my-proxy-broker-$(nodeId).apps.rosa.xxxxxx-zzzzz-yyy.aaaa.cc.openshiftapps.com:443
```

The name `advertisedBrokerAddressPattern` makes it clear that these are advertised addressed.  The port would be optional.  If it is absent, it would default to the bound port of the listenAddress.
