### ISSUE TITLE
Rename MultiTenant -> MultiTenancy

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1774]
Somehow I feel like seeing

```yaml
filterDefinitions:
  - name: mt
    type: Multitenancy
    config: ...
```
and talking about "the multitenancy filter" is _slightly nicer_ than 

```yaml
filterDefinitions:
  - name: mt
    type: MultiTenant
    config: ...
```

I think because a "Multi-tenant filter" could be interpreted as "a filter with multiple tenants" rather than "a filter providing multitenancy". It feels closer to `RecordEncryption`, which is also named for the functionality it provides. 

But note that according to the [google n-gram viewer](https://books.google.com/ngrams/graph?content=multitenant%2Cmulti-tenant%2Cmultitenancy%2Cmulti-tenancy&year_start=1800&year_end=2022&corpus=en&smoothing=3) the world has not really made up its mind about which is the preferred form.

But I accept this is archpedantry, so if people want MultiTenant then I'm not stopping you.

_Originally posted by @tombentley in https://github.com/kroxylicious/kroxylicious/pull/1770#discussion_r1933100165_
