### ISSUE TITLE
Automatic discovery of upstream Kafka bootstrap address

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#1835]
As an application developer I want to leverage the fact that my Kafka cluster is managed by Strimzi so the bootstrap address is discoverable I'd like to take advantage of this to reduce the amount of manual configuration required.

**Comment by robobario** [comment]
The Kafka status may stop presenting bootstrap_servers when reconciliation is paused for a Kafka, and the Kafka resource is in an indeterminate state from the Strimzi Operator's point of view. Should we deprovision the virtual cluster when it is in this state?

**Comment by robobario** [comment]
`ref` is left generic in case we find other things we want to reference, like we could also point it at a k8s service or some other Kafka provisioning CR in future.

`listenerName` is Strimzi specific, so maybe it should be outside the `ref`? Or we could name it something more generic, like an optional `listenerIdentifier` which could be a Strimzi listener name, or a port name on a k8s service.

**Comment by ShubhamRwt** [comment]
Hello, I was working on the code for this issue, I had a question:

Do we need to hard code these value or are these fields something that users can configure accordingly?
```
  ref:
    group: kafka.strimzi.io
    kind: Kafka
    name: my-cluster         # Name of the Kafka CR
    namespace: kafka        # Namespace of the Kafka CR
    listenerName: tls  
```
