### ISSUE TITLE
clusterNetworkAddressConfigProvider config property name is poor

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1840]
We have the name clusterNetworkAddressConfigProvider in our config model.  

It's a poor name because:
*  It's very long, and not very memorable
* The person writing or reading the config has no idea what a "config provider" is, and nor should they.
* It also forces people to have to name one of those implementation, which also have ridiculously long names (`RangeAwarePortPerNodeClusterNetworkAddressConfigProvider`), and which repeat the name of the property. 

We don't really expect (nor want to support) people writing their own networking code, loaded as a plugin, do we? So we're imposing a read cognitive load on users (making it harder to understand this system), but for no benefit to anyone.

Compare what this PR currently gives us:

```yaml
listeners:
  myclusterip:
    clusterNetworkAddressConfigProvider:
      type: RangeAwarePortPerNodeClusterNetworkAddressConfigProvider
      config: 
        bootstrapAddress: xxx
        nodeAddressPattern: xxx
        nodeIdRanges:
          - name: foo
            range:
              startInclusive: 123
              endExclusive: 456
    tls: ...
```

with what we could have:

```yaml
networkPresentations:
  - name: myclusterip
    portIdentifiesNode:
      bootstrapAddress: mycluster-proxy.local:9092
      nodeStartPort: 9092
      nodeIdRanges:
        - name: foo
          startInclusive: 0
          endExclusive: 10
    tls: ...
  - name: myloadbalancer
    sniHostIdentifiesNode:
      bootstrapAddress: mycluster.kafka.com:9192
      advertisedBrokerAddressPattern: broker$(nodeId).mycluster.kafka.com
```

where:
* Renamed `listeners` -> `networkPresentations`
* I'm using an array of objects with an explicit `name` (like we did with `filterDefinitions`)
* In addition to the mandatory `name` those objects support either `portIdentifiesNode` or xor `sniHostIdentifiesNode`, so we're coupling the config schema to the supported networking models.
* I've flattened the `nodeIdRange`

I don't think this is perfect, but I think it is a lot more understandable for users, aligns betters with the conceptual model, and still has room to grow new networking models in the future (but ones which are built in).

To repeat, this could be done in a followup PR. I don't want to block this PR by bikeshedding, but I also feel that our config schema is a hard to understand mess, and adding a new feature like this is an opportunity to take a step backwards and move in a better direction, and we should avoid doubling down on past mistakes.

_Originally posted by @tombentley in https://github.com/kroxylicious/kroxylicious/issues/1823#issuecomment-2670437227_
