### ISSUE TITLE
VirtualClusters should have an explicit name in the config model.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1847]
In the config model, the virtual cluster's name is currently expressed as a key:

```yaml
virtualClusters:
  demo:
    targetCluster:
      bootstrapServers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
```

This is no longer our preferred approach.   We now prefer lists of objects, with an explicit `name:` field.    This is the approach we have take in [NamedFilterDefinitions](https://github.com/kroxylicious/kroxylicious/blob/1d63cf77c77e4afedcc5b0cb059df691f47dd6da/kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/NamedFilterDefinition.java#L26) and it is the approach we are taking to "listeners" in #1823.   The inconsistency will confuse users.

VirtualCluster should be remodelled as a list, and the config model should enforce name uniqueness.   The change should be made in a backwardly compatibility fashion.
