### ISSUE TITLE
Operator: a virtual cluster that references resolvable filters and unresolvable clusterRef causes exception on reconcile

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#1916]
**Describe the bug**
If the operator tries to reconcile a KafkaProxy with a VirtualKafkaCluster having:
1. references to filters that exist
2. references to KafkaClusters that do not exist

Then the reconciliation fails with unhandled exception because we are trying to build a configuration with filter definitions that are never referenced.

**To Reproduce**
1. Run the operator
2. Install the following:
    ```yaml
    ---
    # A Namespace for a single KafkaProxy instance
    apiVersion: v1
    kind: Namespace
    metadata:
      name: my-proxy
      labels:
        app.kubernetes.io/name: kroxylicious
        app.kubernetes.io/component: proxy
    ---
    kind: KafkaProxy
    apiVersion: kroxylicious.io/v1alpha1
    metadata:
      name: example
      namespace: my-proxy
    ---
    kind: KafkaProtocolFilter
    apiVersion: filter.kroxylicious.io/v1alpha1
    metadata:
      name: filter-one
      namespace: my-proxy
    spec:
      type: org.example.some.java.Class
      configTemplate:
        filterOneConfig: true
    ---
    kind: VirtualKafkaCluster
    apiVersion: kroxylicious.io/v1alpha1
    metadata:
      name: bar
      namespace: my-proxy
    spec:
      proxyRef:
        name: example
      targetCluster:
        clusterRef:
          name: missing-cluster
      filters:
        - group: filter.kroxylicious.io
          kind: KafkaProtocolFilter
          name: filter-one
    ```
3. Observe exceptions in the operator logs:
    ```
    2025-03-10 22:36:19 <ReconcilerExecutor-proxyreconciler-81> ERROR io.kroxylicious.kubernetes.operator.ProxyReconciler:219 - Operator had unexpected error
    io.javaoperatorsdk.operator.OperatorException: io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
     - io.kroxylicious.kubernetes.operator.ProxyConfigSecret -> io.kroxylicious.proxy.config.IllegalConfigurationException: 'filterDefinitions' defines filters which are not used in 'defaultFilters' or in any virtual cluster's 'filters': [filter-one.KafkaProtocolFilter.filter.kroxylicious.io]
    ```

**Expected behavior**

The reconciliation should not fail with an unhandled exception. Filters that are not referenced by any accepted virtual cluster should not be included in the definitions list.

I think this points towards the brittleness of statically scattering the cluster-breaking conditions code across many method calls. It's happening because we resolve all the filters, recording cluster conditions if some don't resolve. Then we call another method that checks the cluster refs are resolved, recording cluster conditions if they don't. Then we passed through all the resolved filters.
