### ISSUE TITLE
Consider using Server side apply rather than infrastructure fields to allow user to influence labels/annotations etc on dependant resources

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#2080]
In the API design we've this pattern in a few places.

```
    infrastructure:
      # Controls that let the Developer influence the annotations/labels created on the ingress objects (Service, OpenShift Routes, TLSRoutes etc).
      # If an annotation or label supplied here duplicates one provided by the KafkaProxyIngress, the one defined by the KafkaProxyIngress takes precendence. 
      # The specific use case for this is https://docs.openshift.com/container-platform/4.17/security/certificates/service-serving-certificate.html#add-service-certificate_service-serving-certificate
      # where the developer wishes their VC to use Certificates created by OpenShift (useful for ClusterIP type TLS).
      annotations:
         x: y
      labels:
         x: y
```

The intent is to let the user influence the set of the labels/annotations appearing on the dependant resources (Services etc). 

Whilst this approach is functional, Kubernetes server-side apply offers a more elegant approach.  It should mean the user can annotate/label the dependant objects directly and the Kroxylicious should not overwrite the changes.

@k-wall hasn't used server-side apply before so he can't write much more.  This issue is a reminder to investigate the alternative approach.
