### ISSUE TITLE
Operator: LoadBalancer ingress VKC status

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#2260]
In the VirtualKafkaCluster status we have an ingresses array with status per ingress in the VKC `spec.ingresses` array. This provides a bootstrap address that clients should be able to bootstrap with (if they have DNS and networking lined up such that they can resolve/connect) once the relevant Service is up and running.

So far this is implemented for ClusterIP only. The VKC reconciler is aware of the k8s Service name for the bootstrap service, so it watches it and updates the ingress bootstrap address in the status accordingly.

#2212 implements LoadBalancer ingress, but does not implement any VKC status.

We should report the user-facing bootstrap address in the VKC status, this will be the value supplied by the user (possibly with `$(virtualClusterName)` tokens replaced appropriately) in the KafkaProxyIngress. It should only be set once the shared Service is manifested. Note that this address will require the user to set up their DNS appropriately.

**Comment by SamBarker** [comment]
Should the Reconcilers test that the given bootstrap address are resolvable? Or is the fact that they are on cluster and clients are equally likely to be off cluster negate that value?

**Comment by robobario** [comment]
yeah not entirely sure how applicable it is, maybe the DNS resolution that clients will use to get to `my-bootstrap.thirdparty.dns` won't be resolvable from the proxy pod? That's all kinda off in user responsibility land.

I wonder if we should also add the external IP to this status. Imagining a flow like:

1. I set up my certs for `bootstrap.kafka.com` (plus SANs for the broker nodes or a wildcard like `*.broker.kafka.com`)
2. I create my KafkaProxy, VirtualKafkaCluster etc with downstream TLS and a LoadBalancer KafkaProxyIngress with bootstrap `bootstrap.kafka.com` and broker address pattern `$(nodeId).broker.kafka.com`. // at this point I can't have set up DNS since I don't know the external IP yet
3. Things manifest and in the VKC status I can see my bootstrap address for the ingress is bootstrap.kafka.com:9083 and the external ip is 10.96.123.5
4. I set up my DNS to get `bootstrap.kafka.com` and `*.broker.kafka.com` to resolve to 10.96.123.5
5. off-cluster clients can connect

**Comment by k-wall** [comment]
> yeah not entirely sure how applicable it is, maybe the DNS resolution that clients will use to get to my-bootstrap.thirdparty.dns won't be resolvable from the proxy pod? That's all kinda off in user responsibility land.

Agreed.  We can't assume the address is resolvable from the cluster.

> I wonder if we should also add the external IP to this status.

I had a thought that the ingress section of status wouldn't populated until the underlying LB service had assigned an address.  My duff idea was that this would mean that the address is ready.  Of course this knows nothing about DNS resolvability.

I agree exposing the assigned LB address is a good idea.  I don't think it is necessarily an IP address.  IIRC on AWS, your LB gives you a FQDN.  I'm undecided whether we should do this now.  If we do it now, are we rushing the API, if we don't, we force the user to peep at the service themselves which should be an internal concern. 

If we were to to do, what field from the Service would we need to expose?  How simple is it?

**Comment by k-wall** [comment]
I had a quick poke around reminding myself about how the status LoadBalancer services actually works.  I wanted to understand how one knows when a LB has an external address assigned.

On minikube, here's a before/after running the `minikube tunnel` command.   After running tunnel, the ingress node appeared in the status section with an IP address.

` oc get service -n my-proxy -o yaml`

```
kwall@Oslo loadbalancer-ingress % diff minikube.before minikube.after
23c23
<     resourceVersion: "778"
---
>     resourceVersion: "928"
51c51,54
<     loadBalancer: {}
---
>     loadBalancer:
>       ingress:
>       - ip: 10.107.105.205
>         ipMode: VIP
```

On AWS ROSA, I didn't catch the before state, but the service's status looked like this.  IOW, same as minikube but with a hostname rather than a ip field.

```
  status:
    loadBalancer:
      ingress:
      - hostname: a17e24f4e4d6a4be99f165a03ace7519-667583259.us-east-1.elb.amazonaws.com
 ```

Just for good measure, I checked what the status section of a ClusterIP service looks like:

```
  spec:
    clusterIP: 172.30.236.218
    clusterIPs:
    - 172.30.236.218
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: my-cluster-9292
      port: 9292
      protocol: TCP
      targetPort: 9292
    - name: my-cluster-9293
      port: 9293
      protocol: TCP
      targetPort: 9293
    - name: my-cluster-9294
      port: 9294
      protocol: TCP
      targetPort: 9294
    - name: my-cluster-9295
      port: 9295
      protocol: TCP
      targetPort: 9295
    selector:
      app: kroxylicious
      app.kubernetes.io/component: proxy
      app.kubernetes.io/instance: simple
      app.kubernetes.io/managed-by: kroxylicious-operator
      app.kubernetes.io/name: kroxylicious-proxy
      app.kubernetes.io/part-of: kafka
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
```


It looks to me like we could delay populating the ingress section of the VKC until the load balancer has assigned the address.
