### ISSUE TITLE
Support key material in PEM format (X.509 certificates and PKCS-8 private keys)

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#375]
**Is your feature request related to a problem? Please describe.**

When operating within Kubernetes/Openshift one frequently encounters key material in PEM format (trust anchors and private keys).  It would be convenient if Kroxylicious were able to consume such key material directly, without requiring the user to perform key material translations or other modifications.

This would allow [Kubernetes secret project](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume) to be used to get key material into the pods running Kroxylicious..

Of course, support for JKS and PKCS12 should still be supported too.

**Describe the solution you'd like**

One such example is the [Openshift Service Serving Certificate](https://docs.openshift.com/container-platform/4.13/security/certificates/service-serving-certificate.html).  It generates PKCS#1 private key objects formatted as PEM.  The certificate is X.509 formatted as a PEM.

Here the platform generates a secret for you like so:

```yaml
apiVersion: v1
kind: Secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJU....0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0Eg...tFWS0tLS0tCg==
```

so it would be convenient if I could provide kroxy with configuration like:

```yaml
virtualCluster:
 foo:
    tls:
       type: PEM
       serverCertficate: .../tls.crt
       serverPrivateKey: .../tls.key
```

**Describe alternatives you've considered**

**Additional context**
