### ISSUE TITLE
Absence of PKCS12 keystore password goes undetected until connection time

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#891]
**Describe the bug**

If you are using PKCS12 keystores and you misconfigure it in such a way that the password is not passed, the issue goes undetected until the connection is attempted.   This occurs when configuring the downsteam to present a TLS server certificate or upstream to present a TLS client certification for authentication purposes.

The underlying issue is: https://bugs.openjdk.org/browse/JDK-8287422 

```yaml
    targetCluster:
      bootstrap_servers: myprivatecluster:9092
      tls:
        key:
          keystore: /opt/cert/client.key
          keyPassword: mypass # Typo - ought to have been storePassword
```

**To Reproduce**
1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**
